version: 2

jobs:
  build:
    docker:
      - image: integrationcheckout/ecommerce:wordpress4.9.2.wocommerce3.2.6
    working_directory: ~/cko_wp
    steps:
      - checkout
      - run:
          name: Refresh Wordpress and Install Checkout
          command: |
            sudo service apache2 restart && sudo service mysql restart
            cd /var/www/html/wordpress/wp-content/plugins/ && sudo mv ~/cko_wp/woocommerce-checkout-non-pci-gateway . && sudo mv ~/cko_wp/woocommerce-checkout-pci-gateway .
      - run:
          name: Install dependencies
          command: |
            cd ~/cko_wp/tests && npm i 
      - run:
          name: Run Tests
          command: |
            cd ~/cko_wp/tests && ./node_modules/.bin/chimp config/chimp.js --fail-fast
      - store_artifacts:
          path: ~/cko_wp/tests/screenshots
          destination: Failed-Tests


